### PR TITLE
Add quarto preview instructions, close #23

### LINKED ISSUE #23: How to reproduce the book on Windows?
Just trying this after #22 and hitting this error message:

```
quarto preview
Preparing to preview
[ 1/10] index.qmd

Starting Jupyter kernel...
ERROR: Error executing 'C:/tools/miniconda3/python.exe': The pipe is being closed. (os error 232)
```

Anyone got any ideas? I guess I should set the environment but don't know how...

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Eventually this content wants to be in the appendix as per #19 but for now this is a demo that it works, as tested on my new laptop.

**Comment by Robinlovelace** [comment]
I'm happy that it reproduces the book but putting in as a PR to get feedback. Thanks!

**Comment by anitagraser** [comment]
@Robinlovelace  wouldn't it be good to have this kind of info in the repo readme instead? That's where I would expect it.

**Comment by Robinlovelace** [comment]
> @Robinlovelace wouldn't it be good to have this kind of info in the repo readme instead? That's where I would expect it.

Agreed 👍

**Pull request merged**
