### PR TITLE
Unpin shapely version

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Just put in here to see if tests pass but... Thinking about it we'd need to get the CI building from the environment.yml file to find out, curious to know when we'll be able to use the latest version of this core pkg.

**Comment by Robinlovelace** [comment]
Thoughts on this @anitagraser ? Similar to #36 not a big deal, just seems good to be using latest versions of stuff especially as the project is young.

**Comment by anitagraser** [comment]
Should be fine

**Comment by Robinlovelace** [comment]
> Should be fine

Great, please click Approve on the review request and I'll merge :rocket:

**Review by anitagraser — APPROVED** [review]

**Pull request merged**
