### PR TITLE
Add .devcontainer for #87

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @jsta following your input in #87 I've tried adding a devcontainer. Seem reasonable? Thanks!

**Comment by Robinlovelace** [comment]
Added this message:

image

**Comment by Robinlovelace** [comment]
OK to merge this? Guessing so, can always change in post merge review!

**Comment by michaeldorman** [comment]
> OK to merge this? Guessing so, can always change in post merge review!

Sure, fine with me, thanks. I don't really understand the docker-related things yet...

**Comment by Robinlovelace** [comment]
> I don't really understand the docker-related things yet...

Neither to I! But learning as I go...

**Pull request merged**
